spring.application.name=backend

#aqui será as configurações do banco de dados
spring.datasource.url= jdbc:postgresql://localhost:5432/denuncialixo
spring.datasource.username= postgres
spring.datasource.password= adm2145
spring.datasource.driver-class-name= org.postgresql.Driver

# Configurações do JPA e Hibernate
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

#aqui vai mostrar o endereço que a api vai rodar
server.port=8080